package main

// Generated by https://quicktype.io

type Manifest struct {
	FormatVersion int64    `json:"format_version"`
	Header        Header   `json:"header"`
	Modules       []Module `json:"modules"`
}

type Header struct {
	Description      string  `json:"description"`
	Name             string  `json:"name"`
	UUID             string  `json:"uuid"`
	Version          []int64 `json:"version"`
	MinEngineVersion []int64 `json:"min_engine_version"`
}

type Module struct {
	Description string  `json:"description"`
	Type        string  `json:"type"`
	UUID        string  `json:"uuid"`
	Version     []int64 `json:"version"`
}
