package main

// Generated by https://quicktype.io
// addon manifest json file
type Manifest struct {
	FormatVersion int64    `json:"format_version"`
	Header        Header   `json:"header"`
	Modules       []Module `json:"modules"`
}

type Header struct {
	Description      string  `json:"description"`
	Name             string  `json:"name"`
	UUID             string  `json:"uuid"`
	Version          []int64 `json:"version"`
	MinEngineVersion []int64 `json:"min_engine_version"`
}

type Module struct {
	Description string  `json:"description"`
	Type        string  `json:"type"`
	UUID        string  `json:"uuid"`
	Version     []int64 `json:"version"`
}

// Generated by https://quicktype.io
// java index json file
type JavaIndex struct {
	Objects map[string]Object `json:"objects"`
}

type Object struct {
	Hash string `json:"hash"`
	Size int64  `json:"size"`
}
